baseURL = "https://robmengert.me"
languageCode = "en-us"
title = "Personal Blog of Rob Mengert"
theme = "anatole"
paginate = "10"
pluralizelisttitles = false

[params]
    author = "Rob Mengert"
    brand = "Rob Mengert"
    description = "I'm just a dude in the world."
    profilePicture = "/images/headshot.png"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/robertmengert/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/TheFutonEng/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/RobMengert"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "email"
url = "mailto:rob.mengert@gmail.com"

[menu]

[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url  = "/"

[[menu.main]]
name = "Posts"
identifier = "posts"
weight = 200
url  = "/posts"

[[menu.main]]
name = "About"
identifier = "about"
weight = 300
url  = "/about/"


[taxonomies]
    series = 'series'
    tags = 'tags'