baseURL = "https://robmengert.me"
languageCode = "en-us"
title = "Personal Blog of Rob Mengert"
theme = "poison"
paginate = "10"
pluralizelisttitles = false

[params]
    author = "Rob Mengert"
    brand = "Rob Mengert"
    description = "I'm just a dude in the world"
    brand_image = "/images/headshot.png"
    menu = [
    {Name = "About", URL = "/about/", HasChildren = false},
    {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
    {Name = "Projects", URL = "", External = true, Limit = 5},
    # {Name = "Battleship Solver", URL = "https://battleship.lukeorth.com", External = true, Limit = 5},
    # {Name = "Poison Hugo Theme", URL = "https://github.com/lukeorth/poison", External = true, Limit = 5},
    ]

    github_url = "https://github.com/TheFutonEng/"
    linkedin_url = "https://www.linkedin.com/in/robertmengert/"
    twitter_url = "https://twitter.com/RobMengert"

[taxonomies]
    series = 'series'
    tags = 'tags'