baseURL = "https://robmengert.me"
languageCode = "en-us"
title = "Personal Blog of Rob Mengert"
theme = "anatole"
paginate = "10"
pluralizelisttitles = false

[params]
    author = "Rob Mengert"
    title = "Rob Mengert"
    description = """
    I'm just a dude in the world.
    I enjoy spending time with my family, good beer,
    and digging into tech.
    """
    profilePicture = "/images/headshot.png"
    googleSiteVerify = "l-MmkEB3NftrODT7Ht1-_Cyj_N0gvqdLZAisD7Y_-lA"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/robertmengert/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/TheFutonEng/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/RobMengert"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "email"
url = "mailto:rob.mengert@gmail.com"

[menu]

[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url  = "/"

[[menu.main]]
name = "Posts"
identifier = "posts"
weight = 200
url  = "/posts"

[[menu.main]]
name = "About"
identifier = "about"
weight = 300
url  = "/about"

[[menu.main]]
name = "Certifications"
identifier = "certifications"
weight = 400
url = "/certifications"

[[menu.main]]
name = "Publications"
identifier = "publications"
weight = 500
url = "/publications"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80